services:
  # 1. El micro-contenedor que prepara los permisos automáticamente
  fix-permissions:
    image: alpine:latest
    user: root
    volumes:
      # Mapeamos las carpetas físicas que usa tu servidor
      - ./steamapps:/fix_steamapps:z
      - ./steam:/fix_steam:Z
      - ./backups:/fix_backups:Z
    # Ejecuta el chown usando el UID 1001 y se apaga
    command: /bin/sh -c "chown -R 1001:1001 /fix_steamapps /fix_steam /fix_backups"

  # 2. Tu servidor principal
  abiotic:
    build: .
    container_name: abiotic-factor
    restart: unless-stopped
    
    # Le decimos que NO arranque hasta que fix-permissions haya terminado
    depends_on:
      fix-permissions:
        condition: service_completed_successfully

    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"

    environment:
      WINEDEBUG: "-all"
      WINEESYNC: "1"
      WINEFSYNC: "1"
      ARM64_DEVICE: "adlink"
      SERVER_DIR: "/home/steam/steamcmd/steamapps/common/Abiotic Factor Dedicated Server"
      #SERVER_DIR: "/home/steam/steamcmd/steamapps/common/Abiotic Factor Dedicated Server"
      
      # ---- Server config ----
      MAX_PLAYERS: "6"
      SERVER_NAME: "MyAbioticoReaction"
      SERVER_PASSWORD: "locuron123"      # CHANGE THIS!
      WORLD_SAVE_NAME: "Cascade"

      # ---- Behavior toggles ----
      UPDATE_ON_START: "1"   # Update server on container start
      VALIDATE: "0"          # Set to 1 if you suspect corruption
      BACKUP_ON_START: "1"   # Create backup before starting
      BACKUP_KEEP: "5"       # Number of backups to keep

      LOGGING: "0"
      WARMUP_SECONDS: "0"
      TZ: "America/Asuncion"

    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      # Mapeo directo, sin symlinks
      - "./steamapps:/home/steam/steamcmd/steamapps:z"
      - "./steam:/home/steam/Steam:Z"
      - "./backups:/backups:Z"
      - "/etc/localtime:/etc/localtime:ro"
